'use strict';

/**
 * All lessons data
 */
let lessons = [
    {
        title: '01. Seznámení, prstová abeceda',
        chapters: [
            {
                title: 'Slovní zásoba',
                items: [
                    {id: 'u3NHoRxfgP8', title: 'Ahoj'},
                    {id: '5hAI8Zavolg', title: 'Dobrý den'},
                    {id: 'XAPJWB4-g3Y', title: 'Jméno'},
                    {id: 'OJBj2DYFfO8', title: 'Můj'},
                    {id: 'Z7hEN_jYky8', title: 'Tvůj'},
                    {id: 'ihcjfhUZG0w', title: 'Prstová abeceda'},
                    {id: 'hEuAt4Srptw', title: 'Co?'},
                    {id: 'vRx_8fQJ4Is', title: 'Ano'},
                    {id: 'URhwtA_Bdrs', title: 'Ne'},
                    {id: 'OyJxkhrFZy4', title: 'Děkovat'},
                    {id: 'BEGUfy438Ds', title: 'Prosit'},
                    {id: '2mQVNCNGlq0', title: 'Nemluvit'},
                    {id: 'lS0xez2RMxI', title: 'Přihlásit se'},
                    {id: '9rALYrkVBEo', title: 'Dobře'},
                    {id: 'NFPf-ZAYOEA', title: 'Špatně'},
                    {id: 'jxKEVF5vKJI', title: 'Normálně'},
                    {id: 'E07JSH4ug5k', title: 'Na shledanou'},
                    {id: 'jamf_Dda-Jk', title: 'Co znamená?'},
                    {id: 'cLJ8tRdrQdA', title: 'Ještě jednou opakovat'},
                    {id: 'wLPIJaXErs4', title: 'Položit otázku'},
                    {id: '8ITzxttSNhs', title: 'Nerozumím'},
                    {id: 'XM04LmT7WGU', title: 'Rozumím'},
                    {id: 'Df9qaObJGlc', title: 'Rozumíte?'},
                    {id: 'M9EGs2agdso', title: 'Zeptat se'},
                ],
            },
            {
                title: 'Věty',
                items: [
                    {id: 'SVn-QSRfUys', title: 'Jak se jmenuješ?'},
                    {id: 'cyGAojXeuKo', title: 'Jmenuji se Petr.'},
                    {id: 'umg4TgbUdKs', title: 'Jak se jmenuje?'},
                    {id: 'A6s6csvy0oQ', title: 'Jak se jmenuji?'},
                    {id: 'P3kh9GAdt-8', title: 'Jak se máš?'},
                    {id: 'NO6r8ONEjWY', title: 'Mám se dobře.'},
                    {id: 'm8944yDj7BY', title: 'Mám se špatně.'},
                    {id: 'DNLce0vV9-4', title: 'Mám se normálně.'},
                    {id: 'cLJ8tRdrQdA', title: 'Ještě jednou opakovat.'},
                    {id: 'XM04LmT7WGU', title: 'Rozumím.'},
                    {id: '8ITzxttSNhs', title: 'Nerozumím.'},
                ],
            },
        ],
    },
    {
        title: '02. Já a ti druzí (základní povolání, osobní zájmena)',
        chapters: [
            {
                title: 'Slovní zásoba',
                items: [
                    {id: 'BYfmoYoLhWk', title: 'Kdo?'},
                    {id: 'U_HEKWN4fvs', title: 'Žena'},
                    {id: 'VZveN6e14U8', title: 'Muž'},
                    {id: 'ohC4eggCANE', title: 'Dívka / holka'},
                    {id: 'gGJbYERdl0g', title: 'Chlapec / kluk'},
                    {id: 'ekTjEbBXskE', title: 'Neslyšící'},
                    {id: 'yp1S0UACpbA', title: 'Slyšící'},
                    {id: 'VaQJBt1j9Js', title: 'Ty'},
                    {id: 'yicYdLYUxek', title: 'Já'},
                    {id: 'Ym_iTYFznJw', title: 'On / ona'},
                    {id: 'knS_za7L0CU', title: 'My'},
                    {id: 'ZDpbskc7ipY', title: 'Vy'},
                    {id: 'Y3b4YfNt76A', title: 'Oni'},
                    {id: 'CRTP3d63pIE', title: 'Kdo to je?'},
                    {id: 'lBAClEKck2A', title: 'Lektor'},
                    {id: 'sRVgKu92b4M', title: 'Student'},
                    {id: 'FDDcQuThRfk', title: 'Učit'},
                    {id: 't9MMUKvuJzA', title: 'Učit se'},
                    {id: 'mc3UWL2RLRo', title: 'Český znakový jazyk'},
                    {id: 'gIupZt-z83s', title: 'Pracovat'},
                    {id: 'fguQGry2zug', title: 'Práce'},
                ],
            },
            {
                title: 'Věty',
                items: [
                    {id: 'S2SqLPdHhNY', title: 'Kdo jsem?'},
                    {id: '_mVswW_bmuw', title: 'Jsem lektor?'},
                    {id: 'VCLMTKn_14I', title: 'Ty jsi lektor?'},
                    {id: 'Xf9otPoHwI4', title: 'On/ona je lektor.'},
                    {id: '4VHQsKQF8iQ', title: 'Já jsem lektor a ty jsi student.'},
                    {id: '7Cw8LY5PKcg', title: 'Ty jsi neslyšící?'},
                    {id: 'K5vqpqsTUOs', title: 'Ne, jsem slyšící.'},
                    {id: 'tTXSyN0UdLQ', title: 'Ona je žena?'},
                    {id: 'd-5lm30HhyU', title: 'Jsi žena?'},
                    {id: 'a7QB_peUf_8', title: 'Ano, jsem žena.'},
                    {id: 'yEBq9Ql7C-0', title: 'Jsem muž?'},
                    {id: 'RUDtKnjcEIU', title: 'Já jsem neslyšící?'},
                    {id: '6KcfkpNRLRo', title: 'Já učím znakovat.'},
                    {id: 'aU2JJn1k54Y', title: 'Já se učím znakovat.'},
                    {id: 'lWVI72_6sPI', title: 'Vy se učíte ČZJ.'},
                    {id: 'hp-Hyaqamc8', title: 'Vy jste studenti?'},
                    {id: 'LYBs8WFaF7w', title: 'Jsem student?'},
                    {id: 'Bz6ZkEH_a6A', title: 'On je student?'},
                    {id: '0B_E6X5HtoE', title: 'On/ona pracuje jako lektor.'},
                    {id: 'BSH76JwLYRQ', title: 'Co děláš za práci?'},
                    {id: 'pHeOlE7g15s', title: 'Co dělá za práci?'},
                    {id: 'lOgPiihBB68', title: 'Já pracuji jako doktor.'},
                    {id: 'dJw-CCz4aHs', title: 'On/ona je doktor?'},
                ],
            },
        ],
    },
    {
        title: '03. Rodina (zájmena, věk)',
        chapters: [
            {
                title: 'Slovní zásoba',
                items: [
                    {id: 'lOrCLoXkYSk', title: 'Základní čísla: 1-10'},
                    {id: 'JnMJ5InWHmc', title: 'Přítel/kyně'},
                    {id: 'R1S6R9kXG0I', title: 'Vdovec'},
                    {id: 'iaZ0YhP0oV8', title: 'Vdova'},
                    {id: 'ACM2cjlwD20', title: 'Rodina'},
                    {id: '6kRJTgKuHgg', title: 'Táta'},
                    {id: 'olcDt_-rec4', title: 'Máma'},
                    {id: 'aT2vfHXYkLg', title: 'Děti'},
                    {id: '0uhn7Uk7QHo', title: 'Syn'},
                    {id: '4qxrguVciUM', title: 'Dcera'},
                    {id: 'fZh1CGenskI', title: 'Bratr'},
                    {id: 'vjGypx7vWCw', title: 'Sestra'},
                    {id: '5TMWFA3CGH0', title: 'Pes'},
                    {id: 'YmJi4buSOjo', title: 'Kočka'},
                    {id: 'K1aFAkg5Xn8', title: 'Babička'},
                    {id: 'ApyKGgyTE-8', title: 'Dědeček'},
                    {id: 'tT5dKhqIehE', title: 'Mít  / nemít'},
                    {id: 'vOd4-3x4TmM', title: 'Jeho / její'},
                    {id: 'kcdJwr21ESw', title: 'Kolik?'},
                    {id: 'l8pM2HWjq0g', title: 'Kolik roků?'},
                    {id: 'DSFVTfitYtg', title: 'Rozvedený / rozvedená'},
                    {id: 'xpfqDPt9ASU', title: 'Svobodný / svobodná'},
                    {id: 'uc1rW_tgWOU', title: 'Ženatý / vdaná'},
                    {id: 'sWA4EEJuAIY', title: 'Věk 1-50'},
                ],
            },
            {
                title: 'Věty',
                items: [
                    {id: 'isNcJACZzI0', title: 'Máš mámu a tátu?'},
                    {id: 'bVSWt7zx_Ag', title: 'Máš bratra?'},
                    {id: '1zvp1n4gEts', title: 'Ne, já bratra nemám.'},
                    {id: 'k_QgvXnIOXk', title: 'Nemám bratra, mám sestru.'},
                    {id: 'kYkAtE5qz9A', title: 'Máš děti?'},
                    {id: 'f1-iQDGZEKY', title: 'Já nemám děti.'},
                    {id: 'a-YGrlMHneI', title: 'Ty máš bratra nebo sestru?'},
                    {id: 'FBB_Kf4nBfc', title: 'Nemám babičku, ale mám dědečka.'},
                    {id: '_zfrAVoUOUY', title: 'Má babičku?'},
                    {id: 'lX9WyPozKAE', title: 'Máš psa?'},
                    {id: 'mHIPx4FfqD4', title: 'Ne, já psa nemám.'},
                    {id: 'hswnxIBqbug', title: 'Kolik máš dětí?'},
                    {id: 'wc4j1USNKsQ', title: 'Mám dvě děti.'},
                    {id: 'ta1lvSDsDxs', title: 'Můj táta má psa.'},
                    {id: '62LUpSYORK0', title: 'Moje máma nemá kočku.'},
                    {id: 'ywvGy59iyuU', title: 'Jak se jmenuje tvůj pes?'},
                    {id: 'DyGwsQvkQUU', title: 'Můj pes se jmenuje Bára.'},
                    {id: 'gbRiew9Ib8g', title: 'Jak se jmenuje tvoje dcera?'},
                    {id: 'YVeXpvFUzzw', title: 'Moje dcera se jmenuje Anička.'},
                    {id: 'CnUfMmptwdE', title: 'Je tvůj bratr ženatý?'},
                    {id: '_2zMIwJBVBU', title: 'Je tvoje sestra vdaná?'},
                    {id: 'voCouPLIBjk', title: 'Ano, moje sestra je vdaná.'},
                    {id: 'EwzI_x1GQu8', title: 'Můj táta je rozvedený.'},
                    {id: 'REEKdw0SLfM', title: 'Kolik je ti roků?'},
                    {id: 'q0wVwpdEvSI', title: 'Je mi 25 let.'},
                    {id: '28x1691RtRY', title: 'Kolik let je dětem?'},
                    {id: 'abtstQPGUwg', title: 'Dětem je 5 a 10 let.'},
                    {id: 'MHvTjiCTj0E', title: 'Mé babičce je 70 roků a je vdova.'},
                    {id: 'OnyYAgg3Mq0', title: 'Můj bratr nemá holku.'},
                ],
            },
        ],
    },
    {
        title: '04. Číslovky (cena, telefonní číslo, čas)',
        chapters: [
            {
                title: 'Slovní zásoba',
                items: [
                    {id: 'lOrCLoXkYSk', title: '1-10'},
                    {id: 'bImzXhpVkpA', title: '11 - 20'},
                    {id: 'xGMKEAUdTJE', title: '21 - 30'},
                    {id: 'lmJqjj7MUI8', title: '30 - 100'},
                    {id: 'FFkv2RgBVEM', title: 'Chleba'},
                    {id: '9XnxcnA_4VA', title: 'Rohlík'},
                    {id: 'W15QFBLdPks', title: 'Káva'},
                    {id: 'yRCZQmi_NI8', title: 'Mléko'},
                    {id: 'Dixxvs24GbU', title: 'Pivo'},
                    {id: '-kRLs3Rim2s', title: 'Obchod'},
                    {id: 'htdgb1JX4tc', title: 'Cena'},
                    {id: 'BovN7SBVVqs', title: 'Kolik stojí?'},
                    {id: 'GftY-ejNyuI', title: 'Koruny:1-10,-'},
                    {id: 'DZuA9b85h_Y', title: 'Koruny:10-50,-'},
                    {id: '_425_2SSlmg', title: 'Telefonní číslo'},
                    {id: 'nk1jrPEegmU', title: 'Telefon/mobil'},
                    {id: 'kcdJwr21ESw', title: 'Kolik?'},
                    {id: 'HKL68IYHsgQ', title: 'Kolik hodin?'},
                    {id: '-XceTpHDl5E', title: 'Čas: půl 1h - 12h'},
                ],
            },
            {
                title: 'Věty',
                items: [
                    {id: '6LV49bRZgCc', title: 'Kolik stojí chleba?'},
                    {id: 'qOi7eihz6Xo', title: 'Chleba stojí 15 Kč.'},
                    {id: 'VGxTfVKHRk4', title: 'Kolik stojí pivo?'},
                    {id: 'n66aQIgIJwc', title: 'Pivo stojí 10 Kč.'},
                    {id: 'CAUmN4FoHqY', title: 'Kolik stojí káva?'},
                    {id: 'zexvHHFKX40', title: 'Kolik stojí mléko?'},
                    {id: 'dkZ5OWH-Xxo', title: 'Kolik stojí rohlík?'},
                    {id: 'wjyhytJRdS0', title: 'Co v obchodě koupíš?'},
                    {id: 'ir68FmEUHZM', title: 'V obchodě koupím rohlík, mléko, kávu.'},
                    {id: 'zMkkd6B4BkY', title: 'Kolik koupíš v obchodě rohlíků?'},
                    {id: 'neCjMMqHLs8', title: 'V obchodě koupím pět rohlíků.'},
                    {id: 'aP1_MBL6o0A', title: 'Co tvůj táta v obchodě koupí?'},
                    {id: 'IEKPyoGdFbI', title: 'Tvoje sestra v obchodě kupuje pět rohlíků a tři piva za 50,-.'},
                    {id: 'XuFLedta2CA', title: 'Kočka v obchodě kupuje mléko za cenu 15,-.'},
                    {id: 'FmTQfUwSpAU', title: 'Kolik je hodin?'},
                    {id: 'B9CjdrvI1qE', title: 'V kolik chodíš nakupovat do obchodu?'},
                    {id: '20xfXcdYqxU', title: 'V obchodě nakupuji v půl osmé.'},
                    {id: '5P5GyazUyZU', title: 'Jaké máš telefonní číslo?'},
                    {id: 'XUVOeXlQTew', title: 'Moje telefonní číslo je...'},
                    {id: 'dRPWaCJuWZU', title: 'Prosím telefonní číslo na tvou matku.'},
                    {id: 'TfEVTFbi2cU', title: 'Má tvůj pes mobil?'},
                    {id: '7biLoSuHBtk', title: 'Můj pes mobil nemá.'},
                    {id: '0BRBPY6CZ9g', title: 'Je půl druhé.'},
                ],
            },
        ],
    },
    {
        title: '05. Vlastnosti (popis osob a věcí, přídavná jména)',
        chapters: [
            {
                title: 'Slovní zásoba',
                items: [
                    {id: 'A4n7-ROmqC8', title: 'Postava'},
                    {id: '_riG3FeITtk', title: 'Bohatý'},
                    {id: 'gSlAi-VQRbs', title: 'Chudý'},
                    {id: 'DobmCISnmBs', title: 'Krásný'},
                    {id: 'fxuecfx3OSU', title: 'Ošklivý'},
                    {id: '5qHCk76XlwU', title: 'Čistý'},
                    {id: '6Mc_shbh34w', title: 'Špinavý'},
                    {id: 'oLzbiZe5AJo', title: 'Teplý'},
                    {id: '7F-fNX7GgaY', title: 'Studený'},
                    {id: 'QIeamNtIJGM', title: 'Smutný'},
                    {id: 'DFUL9b27wvA', title: 'Veselý'},
                    {id: 'xAYlLcH-yjk', title: 'Nemocný'},
                    {id: 'vKv_LE_gJ8A', title: 'Zdravý'},
                    {id: 'HuMG9K_lX6s', title: 'Slabý'},
                    {id: 'IzoQ3vXXPDk', title: 'Silný'},
                    {id: 's1mo5T08yYU', title: 'Nový'},
                    {id: 'YKeEbV17z7Y', title: 'Mladý'},
                    {id: 'HDmOaVEsujQ', title: 'Starý'},
                    {id: 'UQ2a715mkhM', title: 'Dobrý'},
                    {id: '72VWIWV-uho', title: 'Špatný'},
                    {id: '2hV-PezMsek', title: 'Hubený'},
                    {id: 'EDQrtWVSSqg', title: 'Tlustý'},
                    {id: '91jGlXInGhA', title: 'Malý'},
                    {id: 'yaAfm7n3nM4', title: 'Velký'},
                    {id: 'ybW4JnVTxZQ', title: 'Malý x Velký 2'},
                    {id: 'OZmsZJVjH1s', title: 'Jaký / jaká / jaké?'},
                    {id: 'TqtPB0PpZWs', title: 'Jak vypadá?'},
                ],
            },
            {
                title: 'Věty',
                items: [
                    {id: 'a5fq39mAXjU', title: 'Je ten chleba dobrý?'},
                    {id: 'o1A-Dcp4IFQ', title: 'Ano, chleba je dobrý.'},
                    {id: 'U-Eez1rqIcM', title: 'Káva je špatná?'},
                    {id: 'kN4aL-Z0KWw', title: 'Pivo je studené nebo teplé?'},
                    {id: 'rUU0kYCLdx4', title: 'Pivo je studené.'},
                    {id: 'NorjqR74WOU', title: 'Kdy jsi byl/a nemocný?'},
                    {id: 'A6k76bj4al0', title: 'Jsi zdravý?'},
                    {id: 'RanUF1EYTH0', title: 'Jsem zdravý.'},
                    {id: 'JF0t0D0nIUU', title: 'Jsi veselý nebo smutný?'},
                    {id: 'CYzq8xJIZL8', title: 'Jsem veselý.'},
                    {id: 'nMjFZMY-i1s', title: 'Jeho/její děti jsou špinavé?'},
                    {id: '9AsyNIO119A', title: 'Děti jsou špinavé.'},
                    {id: 'AuuxXfXB09c', title: 'Tvé děti jsou zlobivé nebo hodné?'},
                    {id: 'RWfW5CWDrPA', title: 'Děti jsou hodné.'},
                    {id: '1eqBLtsRTtc', title: 'Je tvůj táta bohatý?'},
                    {id: 'hMeHhUyORf4', title: 'Kočka je zlobivá?'},
                    {id: 'xVu3-XeUBuw', title: 'Pes je ošklivý?'},
                    {id: 'ynJRzodNwog', title: 'Ne, pes je krásný.'},
                    {id: 'WdOW5k8kO0M', title: 'Jsem mladý nebo starý?'},
                    {id: 'm3xEWZOTF60', title: 'Jsem mladý.'},
                    {id: '5F9FEbuY7e8', title: 'On je mladý?'},
                    {id: 'KdbHYwQKAKA', title: 'Ano, on je mladý.'},
                    {id: '8RC5saH1aCg', title: 'Ne, on je starý.'},
                    {id: 'CHttPvrNe7s', title: 'On je hubený?'},
                    {id: 'f4K5mNLN0cA', title: 'On je malý?'},
                    {id: 'ZBAYNpaEGWs', title: 'Ne, on je velký.'},
                    {id: '8PcTo3brnSY', title: 'On je velký?'},
                    {id: 'WM9olGk6WSk', title: 'Ten pes je malý.'},
                    {id: 'OJcCqZMeUL0', title: 'Jakou postavu má tvoje máma?'},
                    {id: 'HCtBwtmJDYY', title: 'Moje máma je hubená, malá a krásná.'},
                    {id: 'JLqa-3Hpypk', title: 'Jakou postavu má tvůj doktor?'},
                    {id: '3G-jj3l1n-c', title: 'Můj doktor je velký a tlustý.'},
                    {id: 'egBQanhsEAU', title: 'Kolik je mu let?'},
                    {id: 'hE5JlH_Tf5U', title: 'Je mu/jí 30 let.'},
                ],
            },
        ],
    },
    {
        title: '06. Pracovní pomůcky, barvy (prostorová orientace, čas)',
        chapters: [
            {
                title: 'Slovní zásoba',
                items: [
                    {id: 'nWR7YlhBxn8', title: 'Stůl'},
                    {id: 'eRIDLkn11H4', title: 'Židle'},
                    {id: 'VPIEwDRd400', title: 'Tabule'},
                    {id: '989_2euGFvA', title: 'Pero'},
                    {id: 'mLUT9vPybq8', title: 'Okno'},
                    {id: 'MjuEQpukaaw', title: 'Sešit'},
                    {id: 'TrsroWgKRIk', title: 'Kniha'},
                    {id: 'ITwdywkJbEY', title: 'Počítač'},
                    {id: 'JMhh1jhE0DU', title: 'Papír'},
                    {id: 's-oFvIhDNjg', title: 'Barva'},
                    {id: 's1TP6tiyLT4', title: 'Černá'},
                    {id: 'SgegXAoIiS4', title: 'Červená'},
                    {id: '2vndbPZhHy8', title: 'Modrá'},
                    {id: 'Ppt2dkzD3Ww', title: 'Žlutá'},
                    {id: 'WWjFMcgcQhk', title: 'Hnědá'},
                    {id: 'FQVFSRGvDTE', title: 'Zelená'},
                    {id: '-yu69_82mP0', title: 'Bílá'},
                    {id: 'nlQLG77XLQE', title: 'Růžová'},
                    {id: 'FZlyVBimHvQ', title: 'Fialová'},
                    {id: 'jcdewl2d5Tg', title: 'Šedá'},
                    {id: 'qkqlLogyIZk', title: 'Nahoře'},
                    {id: 'EzosuHA1fQ0', title: 'Dole'},
                    {id: 'PnUAjbnr3N0', title: 'Vlevo'},
                    {id: 'P9dMEaUhLfk', title: 'Vpravo'},
                    {id: 'SiH-cvrAqiw', title: 'Nad / pod'},
                    {id: 'Fr5uOhVa87w', title: 'Oblíbený (milovat)'},
                    {id: '10aA6QerIeg', title: 'Neoblíbený (nesnášet)'},
                    {id: 'HKL68IYHsgQ', title: 'Kolik je hodin?'},
                    {id: 'IMe2nHxIvTU', title: 'Hodiny: dopoledne 11 hod. - 24 hod.'},
                    {id: 'dmrsA0R17UA', title: 'Od - do'},
                    {id: 'u2AmxF89Miw', title: 'Kde?'},
                ],
            },
            {
                title: 'Věty',
                items: [
                    {id: 'hoEVndMJFAs', title: 'Kniha je vlevo?'},
                    {id: 'Tvz9dNsdD94', title: 'Okno je vzadu?'},
                    {id: '7K4GM7_j_zc', title: 'Jakou barvu má pero?'},
                    {id: '1smmtJuJobc', title: 'Kde je pero?'},
                    {id: 'kph6vjp6vJk', title: 'Kde je počítač?'},
                    {id: '8AgrBJxPfQ8', title: 'Jakou barvu má tabule?'},
                    {id: '6-4j9gVQGG8', title: 'Jakou barvu má židle?'},
                    {id: 'haQdf6FLLgo', title: 'Jakou barvu nemáš rád?'},
                    {id: 'H9qTSwdA_b0', title: 'Jaká je tvá oblíbená barva?'},
                    {id: 'cBcV4LiC0Xk', title: 'Jaká je její/jeho oblíbená barva?'},
                    {id: 'fjBR0ImAsFA', title: 'Jaká je oblíbená barva tvých dětí?'},
                    {id: 'EawAqnKJPmE', title: 'Od kolika do kolika hodin se učíte ČZJ?'},
                    {id: 'uv2ZnFAOhTM', title: 'Já se ČZJ učím večer od 18:00 do 19:30.'},
                    {id: 'lFrB_wqUvB4', title: 'Kde je kočka?'},
                    {id: '3p9BXvT3Zmk', title: 'Kočka je pod stolem.'},
                    {id: '4wtf4nMIn2w', title: 'Kde je tabule?'},
                ],
            },
        ],
    },
    {
        title: '07. Dny v týdnu, části dne, základní slovesa',
        chapters: [
            {
                title: 'Slovní zásoba',
                items: [
                    {id: 'qukcwdX50pI', title: 'Ráno'},
                    {id: '0nkh_Wr6kLs', title: 'Dopoledne'},
                    {id: 'uxpVEv0gEVI', title: 'Poledne'},
                    {id: 'tfjXn7Nf9Ww', title: 'Odpoledne'},
                    {id: 'f3EuXNYtGwg', title: 'Večer'},
                    {id: 'kG35vADVfjs', title: 'Noc'},
                    {id: 'gkZJlL7_Tlc', title: 'Vstávat'},
                    {id: 'TkkyC6cvd98', title: 'Snídaně'},
                    {id: '8JMn8DA6h3M', title: 'Oběd'},
                    {id: '8sKcEW5Pa-Q', title: 'Večeře'},
                    {id: 'UsZRp0BUw3k', title: 'Kdy?'},
                    {id: 'AYy865LWMiU', title: 'Jíst'},
                    {id: 'YSnellNL1QA', title: 'Pít'},
                    {id: '2Wgl1bKurM0', title: 'Spát'},
                    {id: 'gIupZt-z83s', title: 'Pracovat / práce'},
                    {id: '9OqOq-FyLAE', title: 'Sportovat / sport'},
                    {id: 'O5wta1r7Ets', title: 'Studovat'},
                    {id: 'NH_GmzXr6vA', title: 'Učit se'},
                    {id: 'fyIAmWOoWrM', title: 'Učit'},
                    {id: 'eS8qV_3NLfM', title: 'Pondělí'},
                    {id: 'lCevUX59j6I', title: 'Úterý'},
                    {id: 'D8wjjrANXQU', title: 'Středa'},
                    {id: 'MpnTWyHbdpc', title: 'Čtvrtek'},
                    {id: 'YLuqBIYzHKE', title: 'Pátek'},
                    {id: 'VbfcWxAzsWk', title: 'Sobota'},
                    {id: 'xC2fBQuNjvw', title: 'Neděle'},
                    {id: 'MYpdxEP2f6U', title: 'Den'},
                    {id: 'xeJ5Zki_qc8', title: 'Týden'},
                    {id: 'HrITAqfGw8Y', title: 'Dnes'},
                    {id: 'xNmBzhmswwU', title: 'Včera'},
                    {id: 'Zu8WXyz8Ug0', title: 'Zítra'},
                ],
            },
            {
                title: 'Věty',
                items: [
                    {id: 'xFjCHgBU9lo', title: 'Co je dnes za den?'},
                    {id: 'KnkOCFiPSbI', title: 'Co bylo včera za den?'},
                    {id: 'm3hXHsCAnQs', title: 'Co bude zítra za den?'},
                    {id: 'S1jfVmaP6YY', title: 'Jaký je tvůj oblíbený den?'},
                    {id: 'G7IZIUrUJF4', title: 'Zítra je neděle?'},
                    {id: 'alAV7uk_PKA', title: 'Jaký je jeho/její oblíbený den?'},
                    {id: 'NWUir_SUlWI', title: 'Jaký den nemáš rád/a?'},
                    {id: 'wcwDj3CXYvs', title: 'Co večer piješ?'},
                    {id: 'RHjcZNMstas', title: 'V kolik začíná kurz znakového jazyka?'},
                    {id: 'HqePtF6Oa20', title: 'Vstáváš rád (ráno)?'},
                    {id: 'OXkScZIPWuo', title: 'V kolik šel/šla včera spát?'},
                    {id: 'lYEZRB2a38o', title: 'V kolik včera vstávaly tvoje děti?'},
                    {id: 'mMAKNQbhlew', title: 'V kolik šel včera spát jeho/její bratr?'},
                    {id: 'keiuFtKSH-Y', title: 'Spal/a jsi včera dobře?'},
                    {id: 'OXkScZIPWuo', title: 'V kolik hodin šel/šla včera spát?'},
                    {id: 'OZFE-dblSWI', title: 'V kolik hodin jsi dnes vstával/a?'},
                    {id: 'UnOwbOrdK9w', title: 'Včera šel/šla spát v 11 hod.'},
                    {id: 'KKWeoPjCGLo', title: 'Dnes jsem vstával/a v 8 hod.'},
                    {id: 'l02x5lhWKA0', title: 'Dnes ráno moje děti vstávaly ve 4:30 hod.'},
                ],
            },
        ],
    },
    {
        title: '08. Zájmy / koníčky a volný čas',
        chapters: [
            {
                title: 'Slovní zásoba',
                items: [
                    {id: 'msN4Q7GvXnw', title: 'Koníček'},
                    {id: 'x1OTi5kaYeg', title: 'Cestovat'},
                    {id: '9OqOq-FyLAE', title: 'Sportovat / sport'},
                    {id: 'rtbAEL623hc', title: 'Jezdit na kole'},
                    {id: 'VSdeZjOKLAM', title: 'Plavat'},
                    {id: 'PrZbZI2Cpx0', title: 'Vařit'},
                    {id: 'PrZbZI2Cpx0', title: 'Vařit'},
                    {id: 'FScDEWiOSbo', title: 'Číst'},
                    {id: 'VBcc5sx7v3E', title: 'Lyžovat'},
                    {id: 'mLzxngJEM5o', title: 'Film'},
                    {id: 'TrsroWgKRIk', title: 'Kniha'},
                    {id: 'Ka1BkgEIoeU', title: 'Hudba'},
                    {id: 'mpQ5ctHc20A', title: 'Divadlo'},
                    {id: 'NozjqlwE69s', title: 'TV'},
                    {id: 'B2eXQiEVzkA', title: 'Kino'},
                    {id: 'w7VLqbeohdM', title: 'Výstava'},
                    {id: '1QqRgYp-yJ0', title: 'Uklízet'},
                    {id: 'zOFcberhTZQ', title: 'Dívat se na film'},
                    {id: 'sx5aCgwbyuk', title: 'Sraz s kamarády'},
                    {id: 'cjkTranFxB8', title: 'Bude'},
                    {id: 'nVKkzBNlY5c', title: 'Nebude'},
                    {id: 'ucdYZcZRNFg', title: 'Bylo'},
                    {id: 'a-3N20BpiiI', title: 'Nebylo'},
                    {id: 'Fr5uOhVa87w', title: 'Oblíbený / milovat'},
                    {id: '10aA6QerIeg', title: 'Neoblíbený / nesnášet'},
                ],
            },
            {
                title: 'Věty',
                items: [
                    {id: 'lsmSTArI5ew', title: 'Jaký je tvůj oblíbený film?'},
                    {id: 'FM5X4rp8pok', title: 'Jezdíš rád/a na kole?'},
                    {id: 'q59HXGjY_QQ', title: 'Co rád/a děláš v sobotu a v neděli?'},
                    {id: '3lie71mUlH0', title: 'Co děláš za sport?'},
                    {id: 'V79BLHiaucc', title: 'Máš/nemáš rád/a divadlo?'},
                    {id: 'CezmrUzDz-g', title: 'Já mám rád/a divadlo.'},
                    {id: 'sGeNdJz7xKQ', title: 'Kdy jsi uklízel/a?'},
                    {id: 'vWMqGn1zu2w', title: 'Uklízel/a jsem včera v pondělí.'},
                    {id: '9hqmH-c9pgU', title: 'On/ona uklízí rád?'},
                    {id: 'FODVP3RfpC8', title: 'Byl/a jsi ve středu v kině?'},
                    {id: 'auq145WWXjM', title: 'Ne, ve středu jsem v kině nebyl.'},
                    {id: 'soWzMkxOh_Y', title: 'Byl/a v pondělí na kole?'},
                    {id: 'yRDK3vuX2Bw', title: 'Ano, ten kluk byl v pondělí na kole.'},
                    {id: 'q3zL8yuLldM', title: 'Vaříš rád/a?'},
                    {id: 'Iz1vFkOsgcs', title: 'Ne, já vaření nesnáším.'},
                    {id: 'uNfuZQ3WUxg', title: 'Plave jeho manželka ráda?'},
                    {id: '88qQVwNiQOs', title: 'Ne, jeho manželka plavání nesnáší.'},
                    {id: 'Rgm3Vonyndk', title: 'V kolik hodin jdeš sportovat?'},
                    {id: 'TCOTI6KlSZ8', title: 'Sportuji odpoledne ve tři.'},
                    {id: 'RC6oXG7-YZc', title: 'Půjdeš zítra na výstavu?'},
                    {id: 'y6fbBSIpnm8', title: 'Ne, zítra na výstavu nepůjdu.'},
                ],
            },
        ],
    },
    {
        title: '09. Měsíce, datum',
        chapters: [
            {
                title: 'Slovní zásoba',
                items: [
                    {id: '4UsivwHcsO0', title: 'Měsíc'},
                    {id: '2SqunHrB3Qk', title: 'Narozeniny'},
                    {id: 'Pwk40pYdT-8', title: 'Svátek'},
                    {id: 'RrNfv0dXXd8', title: 'Leden'},
                    {id: '0dR3MaII3SI', title: 'Únor'},
                    {id: '2JQH_7Ru-J0', title: 'Březen'},
                    {id: '3-Pke066mH4', title: 'Duben'},
                    {id: 'kIAuu_mfadc', title: 'Květen'},
                    {id: 'cO2rKCC9L0E', title: 'Červen'},
                    {id: 'e47E6-KqSo8', title: 'Červenec'},
                    {id: '9P6xVIrZpqE', title: 'Srpen'},
                    {id: 'A3WD7Qvbrpo', title: 'Září'},
                    {id: '4tfWi2vwoqU', title: 'Říjen'},
                    {id: 'KVnX65m3E8U', title: 'Listopad'},
                    {id: 'CGETGIBMw3M', title: 'Prosinec'},
                    {id: 'EO3KWhI4WOE', title: 'Datum 1.-31.'},
                    {id: 'ZEZn7U9tsw4', title: 'Teď'},
                ],
            },
            {
                title: 'Věty',
                items: [
                    {id: 'Fwsu3lIfjlY', title: 'Jaký je teď měsíc?'},
                    {id: 'SMUVFIRt1cQ', title: 'Jaký je tvůj oblíbený měsíc?'},
                    {id: 'ild9HF2pNnQ', title: 'Jaký měsíc nemáš rád/a?'},
                    {id: 'YxUgTmJDzaI', title: 'Jaké je tvé oblíbené číslo?'},
                    {id: '0SjkrdNANRE', title: 'Kolikátého je dnes?'},
                    {id: '0nJY8CK0beU', title: 'Kdy máš narozeniny?'},
                    {id: '6RQ-NuhcqV8', title: 'Moje máma má narozeniny 12. listopadu.'},
                    {id: 'ShzW1f-_YCg', title: 'Kdy má narozeniny tvůj manžel?'},
                    {id: 'PQ-feQ3IBbc', title: 'Kdy má narozeniny?'},
                    {id: 'sZ_cBN-zXL8', title: 'Kdy mají narozeniny tvoje děti?'},
                    {id: '3Q_9J8YU2Vc', title: 'Kdy mají narozeniny jeho/její děti?'},
                    {id: '1DQrp9Tye4w', title: 'Jaký je oblíbený měsíc tvého táty?'},
                    {id: 'b6gLfCnMZsU', title: 'Jaký je jeho/její oblíbený měsíc?'},
                    {id: 'OL16J_yRhJo', title: 'Moje oblíbené měsíce jsou květen a srpen.'},
                    {id: '3qK8eMlNvMM', title: 'Jaký měsíc nemají rády tvoje děti?'},
                    {id: 'APHsTyGzA7M', title: 'Moje oblíbené datum je 14. února.'},
                ],
            },
        ],
    },
    {
        title: '10. Počasí, roční období',
        chapters: [
            {
                title: 'Slovní zásoba',
                items: [
                    {id: '27EpcsZ8Ta8', title: 'Počasí'},
                    {id: '6pbNT9v3Gs4', title: 'Bouřka'},
                    {id: 'wjN4yRn9qic', title: 'Mlha'},
                    {id: 'FyPUsVDOOdA', title: 'Sníh (slabý)'},
                    {id: 'r4ujUmYB4bA', title: 'Mráz'},
                    {id: 'b_Z4Npqlx-8', title: 'Oblačno'},
                    {id: 'fwe5s67WY-A', title: 'Mraky'},
                    {id: '4dWHbzuWd3g', title: 'Déšť'},
                    {id: 'AShQYbFQ4Qg', title: 'Slunce'},
                    {id: '13_ta0NJHuA', title: 'Slunce svítí'},
                    {id: 'GLuLwhM84Z4', title: 'Vítr'},
                    {id: '0ST86cXKPsg', title: 'Zima'},
                    {id: 'q5oyfq_GqQY', title: 'Vedro'},
                    {id: '-D817wnCU_4', title: 'Teplo'},
                    {id: '9-78n6E4YYM', title: 'Akorát'},
                    {id: 'aGcsra_dAfo', title: 'Roční období'},
                    {id: 'L_ZXE49jr_s', title: 'Jaro'},
                    {id: 'i1kGwRjcrc8', title: 'Léto'},
                    {id: '0svr9U2slJw', title: 'Podzim'},
                    {id: '0ST86cXKPsg', title: 'Zima'},
                    {id: 'JADN_Wu51aY', title: 'Typ'},
                    {id: 'aLCvWHbYdyY', title: 'Teplota +/-'},
                ],
            },
            {
                title: 'Věty',
                items: [],
            },
        ],
    },
    {
        title: '11./12.Práce a pracovní život, čísla 100 - 50 000',
        chapters: [
            {
                title: 'Slovní zásoba',
                items: [
                    {id: 'E0f7kA6d55c', title: 'Dotazník'},
                    {id: '9l6YYMC1Dmk', title: 'Práce'},
                    {id: 'IixSFqk7yRw', title: 'Pracovní doba'},
                    {id: '0cw3OQ6p8hg', title: 'Pracovní smlouva'},
                    {id: 'AfT4YV0S6mM', title: 'Firma'},
                    {id: 'dTnx65Rd_wc', title: 'Dovolená'},
                    {id: 'KP1ZIj3WSzg', title: 'Mateřská dovolená'},
                    {id: 'phNHuiOCsLg', title: 'E-mail'},
                    {id: 'DbeWQnntwWA', title: 'Nepracuji'},
                    {id: 'J1AKZ2aJCZI', title: 'Neschopenka'},
                    {id: 'hnvf8td6PqY', title: 'Občanský průkaz'},
                    {id: 'xWJNVP3DCKI', title: 'Výplata'},
                    {id: 'V1Uam40RPqY', title: 'Podnikatel'},
                    {id: 'EDR7ZJum5iU', title: 'Řidičský průkaz'},
                    {id: 'L6QruvHcKzU', title: 'ZTP'},
                    {id: 'IFxZUvD9uwE', title: 'Živnotenský list'},
                    {id: 'Twr1uWseNN4', title: 'Životopis'},
                    {id: 'SlxBnoK61PU', title: 'Důchod'},
                    {id: 'NTObKZ1NtmE', title: 'Nezaměstnaný'},
                    {id: 'usCBL7q7KHw', title: 'Škola'},
                    {id: 'i3ul6O-UfyQ', title: '100 - 500 Kč'},
                    {id: 'PB2nEJz-BKs', title: '500 - 1.000 Kč'},
                    {id: 'Ac7t7c9UfsM', title: '1 000 - 10 000 Kč'},
                    {id: '2PpFgQXKTVw', title: '10 000 - 20 000 Kč'},
                    {id: 'd5BYOYqq-Ig', title: '6 000 - 20 000 Kč (alt.)'}
                ],
            },
            {
                title: 'Věty',
                items: [],
            },
        ],
    },
    {
        title: '13. Doprava',
        chapters: [
            {
                title: 'Slovní zásoba',
                items: [
                    {id: 'rpAzeqxw-AY', title: 'Auto'},
                    {id: 'oGpwpn3X9KU', title: 'Loď'},
                    {id: 'BfBoc26iMRk', title: 'Autobus'},
                    {id: 'ha9fPNT-N-I', title: 'Metro'},
                    {id: 'puVvMAivEhY', title: 'Tramvaj'},
                    {id: 'qJYBGAwPQ0s', title: 'Trolejbus'},
                    {id: 'ZQJiYsVd_WQ', title: 'Letadlo'},
                    {id: 'PjV-vGz-2eI', title: 'Vlak'},
                    {id: 'KKAghTMHVpI', title: 'Nádraží'},
                    {id: 'dIH6lSJmYdw', title: 'Doprava'},
                    {id: 'L9Lt-YGYiS8', title: 'Dům / DomůDŮMDOMŮ'},
                    {id: 'WXYUL4puyx0', title: 'Jak dlouho?'},
                    {id: 'fcbywNa1Lq0', title: 'Zastávka'},
                    {id: 'R5BJf_BlKVs', title: 'Jet'},
                    {id: 'N8ifegZaMnU', title: 'Jít'},
                    {id: 'qJU7279u_zU', title: 'Jízdní řád'},
                    {id: 'omxOQW7oN-Q', title: 'Lístek'},
                    {id: 'Fu1G3zKNKV8', title: 'Sleva'},
                    {id: 'u5A6UICroOA', title: 'Odjezd'},
                    {id: 'Zm9-WihgjIM', title: 'Přijezd'},
                    {id: 'UpHX-46NVdQ', title: 'Nastoupit'},
                    {id: 'HuU0f0noPqc', title: 'Vystoupit'},
                    {id: 'ofhUz_NN2z0', title: 'Přestupovat'},
                    {id: 'yQagjZ0o1k8', title: 'Odlet'},
                    {id: 'ie_kJ8RlLA0', title: 'Přílet'},
                    {id: 'INVsf_mMMzA', title: 'Doma'}
                ],
            },
            {
                title: 'Věty',
                items: [],
            },
        ],
    },
    {
        title: '14. Byt a bydlení',
        chapters: [
            {
                title: 'Slovní zásoba',
                items: [
                    {id: 'e6a6OpcQr6g', title: 'Bydlet'},
                    {id: 'phYkZ4PUSsE', title: 'Byt'},
                    {id: 'L9Lt-YGYiS8', title: 'Dům'},
                    {id: 'BtZkZd64LxY', title: 'Pokoj'},
                    {id: 'VXrCmLWcKhs', title: 'Dětský pokoj'},
                    {id: 'moZp2jFgIcY', title: 'Kuchyně'},
                    {id: 'Be35oucM3ws', title: 'Světlo/rozsvítit'},
                    {id: 'XTz4B3jLvM4', title: 'Ložnice'},
                    {id: 'HXo3uEyERPM', title: 'Obývák'},
                    {id: 'poiAjKi_Ybo', title: 'Vlastní'},
                    {id: '7op5luwoKio', title: 'Kancelař'},
                    {id: '1zymc3BkGC4', title: 'Koupelna'},
                    {id: 'T8eXIqFyzRw', title: 'Záchod'},
                    {id: 'z0CVBUcTO3Y', title: 'Nábytek'},
                    {id: '7dxJqHvAhH4', title: 'Gauč'},
                    {id: '9hfMYEA45GU', title: 'Postel'},
                    {id: 'SZtS4XCEQb8', title: 'Skříň'},
                    {id: 'cT8GbeV0rUA', title: 'Koberec'},
                    {id: '4mx2dJMJCzg', title: 'Město'},
                    {id: '97ijuij6wdw', title: 'Vesnice'},
                    {id: '6vX6Ao1VUjk', title: 'Stěhovat'}
                ],
            },
            {
                title: 'Věty',
                items: [],
            },
        ],
    },
    {
        title: '15. Části těla a zdraví',
        chapters: [
            {
                title: 'Slovní zásoba',
                items: [
                    {id: 'XwydN1wXovo', title: 'Tělo'},
                    {id: 'FcjFggzxmuc', title: 'Ruka'},
                    {id: 'CRCRRAVmIhg', title: 'Noha'},
                    {id: 'SBzVh2c8ovc', title: 'Břicho'},
                    {id: 'CNLEdC2xNfs', title: 'Krk'},
                    {id: '7HEify9jP7o', title: 'Hlava'},
                    {id: '75QgUZxsIuQ', title: 'Zub'},
                    {id: '6LXuREg_85s', title: 'Chřipka'},
                    {id: '89x3EBXcMzw', title: 'Rýma'},
                    {id: 'VZmCVfgkiac', title: 'Kašel'},
                    {id: 'CjRPrBOH9Zg', title: 'Průjem'},
                    {id: '-4aJNaJERis', title: 'Zvracet - 1'},
                    {id: 'mpjvlMRZuJ0', title: 'Zvracet - 2'},
                    {id: 'ALLpsjdKWVw', title: 'Operace'},
                    {id: '9sNQF2idKYA', title: 'Krev'},
                    {id: 'mqq7203eWxk', title: 'Ležet'}
                ],
            },
            {
                title: 'Věty',
                items: [],
            },
        ],
    }
];

/**
 * Build up the navigation menu
 */
let navEl = document.querySelector('.l-wrapper__nav');
let navHtml = '';

for (let lesson of lessons) {
    navHtml += `<h2>${lesson.title}</h2>`;

    for (let chapter of lesson.chapters) {
        navHtml += `<h3>${chapter.title}</h3>`;

        navHtml += `<ul>`;

        for (let item of chapter.items) {
            navHtml += `<li class="link" data-id="${item.id}" data-title="${item.title}">${item.title}</li>`;
        }

        navHtml += `</ul>`;


    }
}

navEl.innerHTML = navHtml;


/**
 * Event listeners
 */
document.querySelector('.l-wrapper__nav').addEventListener('click', function (e) {
        if (e.target && e.target.matches('.link')) {
            document.querySelector('.video__title').textContent = e.target.dataset.title;
            document.querySelector('.video__player').src = `https://www.youtube.com/embed/${e.target.dataset.id}?autoplay=1&rel=0&showinfo=0`;
        }
    });
